# Generated by Django 2.0.4 on 2018-04-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dowhat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.AlterModelTable(
            name='member',
            table='Member',
        ),
        migrations.AlterModelTable(
            name='task',
            table='Task',
        ),
    ]
