# Generated by Django 2.0.4 on 2018-04-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dowhat', '0002_auto_20180416_1904'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='members',
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
    ]
